# Generated by Django 6.0.3 on 2026-04-08 23:31

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=apps.users.models.generate_uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
