# Generated by Django 6.0.3 on 2026-04-06 04:21

import django.contrib.postgres.search
import django.utils.timezone
import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "content",
                    models.TextField(help_text="Write your blog post using Markdown"),
                ),
                ("content_html", models.TextField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DF", "Draft"),
                            ("PB", "Published"),
                            ("AR", "Archived"),
                        ],
                        default="DF",
                        max_length=2,
                    ),
                ),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.SearchVector(
                                "title", config="english"
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "content", config="english"
                            ),
                            django.contrib.postgres.search.SearchConfig("english"),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
