# Generated by Django 6.0.3 on 2026-04-08 23:31

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=apps.posts.models.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
